name: Kong Deployment
 
on:
  push:
    branches:
      - main
   
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Download Deck CLI
        run: |
            curl -sL https://github.com/kong/deck/releases/download/v1.35.0/deck_1.35.0_linux_amd64.tar.gz -o deck.tar.gz
            tar -xf deck.tar.gz -C /tmp
            sudo cp /tmp/deck /usr/local/bin/
 
      - name: Ping Kong Admin API
        run:  deck gateway ping --konnect-token kpat_X2fMboQP4nsJ2iEbRN952UZq6eawhxArtjrNfRwm4xfwvZp5v --konnect-addr https://us.api.konghq.com --tls-skip-verify
 
      - name: Generate Kong Configurations
        run: |
            deck file openapi2kong -s ./Billing/billing.yaml |
            deck file patch ./Billing/patches.yaml |
            deck file add-tags -o ./Output/kong-billing.yaml --selector "$.services[*]" --selector "$.services[*].routes[*]" billing
 
      - name: Merge Kong Configurations
        run: deck file merge Output/kong-billing.yaml -o Merging/kong-combined.yaml
 
      - name: Sync Kong Configurations
        run: deck gateway sync --konnect-addr https://us.api.konghq.com --tls-skip-verify -s Merging/kong-combined.yaml --select-tag email
 
